### ISSUE TITLE
Installing issue.

### ISSUE THREAD

**Issue by tumantou** [matsukik/RTsurvival#1]
When I install the software, the following errors happen. I am not sure whether you would like to help me solve the problem.

Downloading GitHub repo matsukik/RTsurvival@master
from URL https://api.github.com/repos/matsukik/RTsurvival/zipball/master
Installing RTsurvival
"C:/R3.4.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore  \
  --quiet CMD INSTALL  \
  "C:/Users/Administrator/AppData/Local/Temp/RtmpG0M5Ls/devtools271871b3531a/matsukik-RTsurvival-105092d"  \
  --library="C:/Users/Administrator/Documents/R/win-library/3.4"  \
  --install-tests 

* installing *source* package 'RTsurvival' ...
** libs

*** arch - i386
C:\Rtools\mingw_32\bin\nm.exe: surv_curv.o: File format not recognized
c:/Rtools/mingw_32/bin/gcc -shared -s -static-libgcc -o RTsurvival.dll tmp.def surv_curv.o -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/R3.4.0/bin/i386 -lR
surv_curv.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'RTsurvival'
* removing 'C:/Users/Administrator/Documents/R/win-library/3.4/RTsurvival'
Installation failed: Command failed (1)

**Comment by matsukik** [comment]
The error is caused by the file src/surv_curv.o, which is an architecture/OS specific compiled file that should not be included as a part of the package source. My apologies. I've removed the file and now you should be able to compile without a problem.

**Comment by tumantou** [comment]
Yes, you are right, and thanks for your responses.
